apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationRuntime
metadata:
  name: demo
spec:
  barURL:
  - https://github.com/DanRoseus/cp4i-examples/blob/main/bars/test-1.bar?raw=true
  - https://github.com/DanRoseus/cp4i-examples/blob/main/bars/test-2.bar?raw=true
  configurations:
  - barauth-unauthenticated
  license:
    accept: true
    license: L-MJTK-WUU8HE
    use: CloudPakForIntegrationNonProductionFREE
  version: "12.0"
  routes:
    disabled: true
  forceFlowsHTTPS:
    enabled: true
  forceFlowBasicAuth:
    enabled: true