apiVersion: apiconnect.ibm.com/v1beta1
kind: Product
metadata:
  name: demo
spec:
  state: Published
  definition:
    product: 1.0.0
    info:
      name: Demo
      title: Demo
      version: "1.0"
    plans:
      default-plan:
        approval: false
        description: Default Plan
        rate-limits:
          default:
            value: 100/1hour
        title: Default Plan
  apis:
    integrationRuntimes:
    - name: demo
  share:
    apim:
      catalog: demo
      credentialsSecret: apim-credentials
      providerOrg: jammy
