kind: Secret
apiVersion: v1
metadata:
  name: ia-barauth-unauthenticated
data:
  configuration: >-
    eyJhdXRoVHlwZSI6IkJBU0lDX0FVVEgiLCJjcmVkZW50aWFscyI6eyJ1c2VybmFtZSI6IiIsInBhc3N3b3JkIjoiIn19Cg==
type: Opaque
---
apiVersion: appconnect.ibm.com/v1beta1
kind: Configuration
metadata:
  name: ia-barauth-unauthenticated
spec:
  secretName: ia-barauth-unauthenticated
  type: barauth
  version: 12.0.8.0-r2

