apiVersion: integration.ibm.com/v1beta1
kind: IntegrationAssembly
metadata:
  name: ia-demo
spec:
  license:
    accept: true
    license: L-JTPV-KYG8TF
    use: CloudPakForIntegrationNonProduction
  managedInstances:
    list:
      - kind: QueueManager
        metadata:
          name: demo-api-qm
  managedIntegrations:
    list:
      - kind: IntegrationRuntime
        metadata:
          name: ia-demo
        spec:
          barURL:
            - >-
              https://github.com/DanRoseus/cp4i-examples/blob/main/bars/test-1.bar?raw=true
            - >-
              https://github.com/DanRoseus/cp4i-examples/blob/main/bars/test-2.bar?raw=true
          configurations:
            - ia-barauth-unauthenticated
          forceFlowBasicAuth:
            enabled: true
          forceFlowsHTTPS:
            enabled: true
          routes:
            disabled: true
      - kind: Product
        metadata:
          name: ia-demo
        spec:
          apis:
            integrationRuntimes:
              - name: ia-demo
          definition:
            info:
              name: IA-Demo
              title: IA-Demo
              version: '1.0'
            plans:
              default-plan:
                approval: false
                description: Default Plan
                rate-limits:
                  default:
                    value: 100/1hour
                title: Default Plan
            product: 1.0.0
          share:
            apim:
              catalog: demo
              credentialsSecret: apim-credentials
              providerOrg: jammy
          state: Published
  storage:
    readWriteOnce:
      class: block-storage
  version: 16.1.0
